# Códigos Aula 4 - Introdução à Fundamentos de Programação, Dados e Estatística para Inteligência Artificial

## De registros para tabelas

In [ ]:
pacientes = [
    {"id_paciente": 101, "idade": 68, "internacoes_anteriores": 2,
     "servico": "Cardiologia", "readmissao_30d": False},
    {"id_paciente": 102, "idade": 45, "internacoes_anteriores": 0,
     "servico": "Clínica Médica", "readmissao_30d": True},
    {"id_paciente": 103, "idade": 72, "internacoes_anteriores": 3,
     "servico": "Cardiologia", "readmissao_30d": True},
    {"id_paciente": 104, "idade": 51, "internacoes_anteriores": 1,
     "servico": "Neurologia", "readmissao_30d": False}
]

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(pacientes)
df

   id_paciente  idade  internacoes_anteriores         servico  readmissao_30d
0          101     68                       2     Cardiologia           False
1          102     45                       0  Clínica Médica            True
2          103     72                       3     Cardiologia            True
3          104     51                       1      Neurologia           False

In [ ]:
print(type(df))
print(type(df["idade"][0]))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.int64'>

## Escrita e Leitura de arquivos

Escrevendo um csv

In [ ]:
df.to_csv("pacientes_aula4.csv", index=False)

Escrevendo um excel

In [ ]:
df.to_excel("pacientes_aula4.xlsx", index=False)

Lendo um arquivo csv

In [ ]:
df_csv = pd.read_csv("pacientes_aula4.csv")
df_csv

   id_paciente  idade  internacoes_anteriores         servico  readmissao_30d
0          101     68                       2     Cardiologia           False
1          102     45                       0  Clínica Médica            True
2          103     72                       3     Cardiologia            True
3          104     51                       1      Neurologia           False

Lendo um arquivo excel

In [ ]:
df_excel = pd.read_excel("pacientes_aula4.xlsx")
df_excel

   id_paciente  idade  internacoes_anteriores         servico  readmissao_30d
0          101     68                       2     Cardiologia           False
1          102     45                       0  Clínica Médica            True
2          103     72                       3     Cardiologia            True
3          104     51                       1      Neurologia           False

## Inspeções Iniciais

In [ ]:
df_csv.head()

   id_paciente  idade  internacoes_anteriores         servico  readmissao_30d
0          101     68                       2     Cardiologia           False
1          102     45                       0  Clínica Médica            True
2          103     72                       3     Cardiologia            True
3          104     51                       1      Neurologia           False

In [ ]:
df_csv.shape

(4, 5)

In [ ]:
df_csv.columns

Index(['id_paciente', 'idade', 'internacoes_anteriores', 'servico',
       'readmissao_30d'],
      dtype='object')

In [ ]:
df_csv.dtypes

id_paciente                int64
idade                      int64
internacoes_anteriores     int64
servico                   object
readmissao_30d              bool
dtype: object

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_paciente             4 non-null      int64
 1   idade                   4 non-null      int64
 2   internacoes_anteriores  4 non-null      int64
 3   servico                 4 non-null      object
 4   readmissao_30d          4 non-null      bool
dtypes: bool(1), int64(3), object(1)
memory usage: 264.0+ bytes

# Seleção e filtros

In [ ]:
df_csv["idade"]

0    68
1    45
2    72
3    51
Name: idade, dtype: int64

In [ ]:
df_csv[["idade", "servico", "readmissao_30d"]]

   idade         servico  readmissao_30d
0     68     Cardiologia           False
1     45  Clínica Médica            True
2     72     Cardiologia            True
3     51      Neurologia           False

In [ ]:
df_csv.iloc[0]

id_paciente                       101
idade                              68
internacoes_anteriores              2
servico                   Cardiologia
readmissao_30d                  False
Name: 0, dtype: object

In [ ]:
df_csv.iloc[0:3]

   id_paciente  idade  internacoes_anteriores         servico  readmissao_30d
0          101     68                       2     Cardiologia           False
1          102     45                       0  Clínica Médica            True
2          103     72                       3     Cardiologia            True

In [ ]:
df_csv.loc[0, "idade"]

np.int64(68)

In [ ]:
df_csv.loc[0:2, ["idade", "servico"]]

   idade         servico
0     68     Cardiologia
1     45  Clínica Médica
2     72     Cardiologia

In [ ]:
filtro_idade = df_csv["idade"] >= 65
filtro_idade

0     True
1    False
2     True
3    False
Name: idade, dtype: bool

In [ ]:
pacientes_65_mais = df_csv[df_csv["idade"] >= 65]
pacientes_65_mais

   id_paciente  idade  internacoes_anteriores      servico  readmissao_30d
0          101     68                       2  Cardiologia           False
2          103     72                       3  Cardiologia            True

In [ ]:
cardiologia = df_csv[df_csv["servico"] == "Cardiologia"]
cardiologia

   id_paciente  idade  internacoes_anteriores      servico  readmissao_30d
0          101     68                       2  Cardiologia           False
2          103     72                       3  Cardiologia            True

In [ ]:
df_renomeado = df_csv.rename(columns={
    "internacoes_anteriores": "internacoes",
    "readmissao_30d": "readmissao"
})

df_renomeado

   id_paciente  idade  internacoes         servico  readmissao
0          101     68            2     Cardiologia       False
1          102     45            0  Clínica Médica        True
2          103     72            3     Cardiologia        True
3          104     51            1      Neurologia       False